import { Activity, Recommendation } from './types';

export const ACTIVITIES: Activity[] = [
  {
    id: 'car-petrol',
    name: 'Petrol Car',
    category: 'transport',
    unit: 'km',
    emissionFactor: 0.17,
    icon: 'Car',
  },
  {
    id: 'bus',
    name: 'Public Bus',
    category: 'transport',
    unit: 'km',
    emissionFactor: 0.1,
    icon: 'Bus',
  },
  {
    id: 'meat-beef',
    name: 'Beef Meal',
    category: 'food',
    unit: 'servings',
    emissionFactor: 6.5,
    icon: 'Beef',
  },
  {
    id: 'meat-chicken',
    name: 'Chicken Meal',
    category: 'food',
    unit: 'servings',
    emissionFactor: 1.3,
    icon: 'Utensils',
  },
  {
    id: 'electricity',
    name: 'Electricity Usage',
    category: 'energy',
    unit: 'kWh',
    emissionFactor: 0.4,
    icon: 'Zap',
  },
  {
    id: 'heating-gas',
    name: 'Gas Heating',
    category: 'energy',
    unit: 'hours',
    emissionFactor: 1.2,
    icon: 'Flame',
  },
  {
    id: 'flight-short',
    name: 'Short Flight',
    category: 'transport',
    unit: 'hours',
    emissionFactor: 150,
    icon: 'Plane',
  },
  {
    id: 'plastic-bottle',
    name: 'Plastic Bottle',
    category: 'lifestyle',
    unit: 'bottles',
    emissionFactor: 0.1,
    icon: 'GlassWater',
  },
  {
    id: 'water-usage',
    name: 'Water Usage',
    category: 'lifestyle',
    unit: 'liters',
    emissionFactor: 0.001,
    icon: 'Droplets',
  },
  {
    id: 'shopping-new',
    name: 'New Product Purchase',
    category: 'lifestyle',
    unit: 'items',
    emissionFactor: 25,
    icon: 'ShoppingBag',
  },
];

export const RECOMMENDATIONS: Recommendation[] = [
  {
    activityId: 'car-petrol',
    alternativeName: 'Cycling / Walking',
    alternativeFactor: 0,
    description: 'Switching to cycling or walking for short trips eliminates transport emissions entirely.',
  },
  {
    activityId: 'car-petrol',
    alternativeName: 'Electric Vehicle',
    alternativeFactor: 0.05,
    description: 'EVs significantly reduce per-km emissions compared to internal combustion engines.',
  },
  {
    activityId: 'meat-beef',
    alternativeName: 'Plant-based Meal',
    alternativeFactor: 0.5,
    description: 'Plant-based diets have a much lower environmental impact than red meat.',
  },
  {
    activityId: 'electricity',
    alternativeName: 'Solar Energy',
    alternativeFactor: 0.05,
    description: 'Renewable energy sources like solar can cut your household carbon footprint by up to 90%.',
  },
  {
    activityId: 'plastic-bottle',
    alternativeName: 'Reusable Bottle',
    alternativeFactor: 0.001,
    description: 'Using a reusable bottle prevents hundreds of plastic bottles from entering landfills and reduces production emissions.',
  },
  {
    activityId: 'water-usage',
    alternativeName: 'Water Conservation',
    alternativeFactor: 0.0005,
    description: 'Reducing water waste and using efficient fixtures can halve the energy required for water treatment and pumping.',
  },
  {
    activityId: 'shopping-new',
    alternativeName: 'Second-hand / Refurbished',
    alternativeFactor: 2,
    description: 'Buying second-hand avoids the massive carbon footprint of manufacturing new products and extends item lifecycles.',
  },
];
